artifact_uri: file:///Users/nikhilprao/Documents/GridCast-Intelligent-Energy-Demand-Forecasting/notebooks/models/mlflow_artifacts/236928468635040117/b4d538bd900d4ea7902188090cd82d5f/artifacts
end_time: 1758136802211
entry_point_name: ''
experiment_id: '236928468635040117'
lifecycle_stage: active
run_id: b4d538bd900d4ea7902188090cd82d5f
run_name: Prophet
source_name: ''
source_type: 4
source_version: ''
start_time: 1758136802189
status: 3
tags: []
user_id: nikhilprao
