artifact_uri: file:///Users/nikhilprao/Documents/GridCast-Intelligent-Energy-Demand-Forecasting/notebooks/models/mlflow_artifacts/236928468635040117/690cabdba1a64b47aed9cd1964cbdb77/artifacts
end_time: 1758136805728
entry_point_name: ''
experiment_id: '236928468635040117'
lifecycle_stage: active
run_id: 690cabdba1a64b47aed9cd1964cbdb77
run_name: CatBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1758136803720
status: 3
tags: []
user_id: nikhilprao
