artifact_uri: file:///Users/nikhilprao/Documents/GridCast-Intelligent-Energy-Demand-Forecasting/notebooks/models/mlflow_artifacts/236928468635040117/84713238e0294191af022d73ffd706ce/artifacts
end_time: 1758136787484
entry_point_name: ''
experiment_id: '236928468635040117'
lifecycle_stage: active
run_id: 84713238e0294191af022d73ffd706ce
run_name: SARIMA
source_name: ''
source_type: 4
source_version: ''
start_time: 1758136787360
status: 3
tags: []
user_id: nikhilprao
