artifact_location: file:///Users/nikhilprao/Documents/GridCast-Intelligent-Energy-Demand-Forecasting/notebooks/models/mlflow_artifacts/236928468635040117
creation_time: 1758135440588
experiment_id: '236928468635040117'
last_update_time: 1758135440588
lifecycle_stage: active
name: GridCast_Complete_Analysis
