artifact_uri: file:///Users/nikhilprao/Documents/GridCast-Intelligent-Energy-Demand-Forecasting/notebooks/models/mlflow_artifacts/236928468635040117/70ca37dd4ead4ca09b6fefb677545460/artifacts
end_time: 1758136803705
entry_point_name: ''
experiment_id: '236928468635040117'
lifecycle_stage: active
run_id: 70ca37dd4ead4ca09b6fefb677545460
run_name: XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1758136802264
status: 3
tags: []
user_id: nikhilprao
